<a href="https://colab.research.google.com/github/Nilaav/ICT-Assignment/blob/main/ICT_ASSIGNMENT_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Case Study on Numpy and Pandas

In [2]:
from google.colab import files
uploaded = files.upload()

Saving auto-mpg (1).csv to auto-mpg (1).csv


In [3]:
import numpy as np
import pandas as pd

df = pd.read_csv('auto-mpg (1).csv')
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [4]:
df['horsepower'] = df['horsepower'].replace('?', np.nan).astype(float)
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mean())

##NumPy Problems

In [5]:
#1
mpg = df['mpg'].to_numpy()

mean_mpg = mpg.mean()
median_mpg = np.median(mpg)
std_mpg = mpg.std()
count_gt_25 = np.sum(mpg > 25)

mean_mpg, median_mpg, std_mpg, count_gt_25

(np.float64(23.514572864321607),
 np.float64(23.0),
 np.float64(7.806159061274433),
 np.int64(158))

In [6]:
#2
cars_gt_6 = df[df['cylinders'] > 6]['car name'].to_numpy()
cars_gt_6

array(['chevrolet chevelle malibu', 'buick skylark 320',
       'plymouth satellite', 'amc rebel sst', 'ford torino',
       'ford galaxie 500', 'chevrolet impala', 'plymouth fury iii',
       'pontiac catalina', 'amc ambassador dpl', 'dodge challenger se',
       "plymouth 'cuda 340", 'chevrolet monte carlo',
       'buick estate wagon (sw)', 'ford f250', 'chevy c20', 'dodge d200',
       'hi 1200d', 'chevrolet impala', 'pontiac catalina brougham',
       'ford galaxie 500', 'plymouth fury iii', 'dodge monaco (sw)',
       'ford country squire (sw)', 'pontiac safari (sw)',
       'chevrolet impala', 'pontiac catalina', 'plymouth fury iii',
       'ford galaxie 500', 'amc ambassador sst', 'mercury marquis',
       'buick lesabre custom', 'oldsmobile delta 88 royale',
       'chrysler newport royal', 'amc matador (sw)',
       'chevrolet chevelle concours (sw)', 'ford gran torino (sw)',
       'plymouth satellite custom (sw)', 'buick century 350',
       'amc matador', 'chevrolet malibu

In [7]:
#3
weight = df['weight'].to_numpy()
np.percentile(weight, [25, 50, 75])

array([2223.75, 2803.5 , 3608.  ])

In [8]:
#4
acc = df['acceleration'].to_numpy()
acc_normalized = (acc - acc.min()) / (acc.max() - acc.min())
acc_normalized[:5]

array([0.23809524, 0.20833333, 0.17857143, 0.23809524, 0.14880952])

In [9]:
#5
horsepower_updated = df['horsepower'].to_numpy() * 1.1
horsepower_updated[:5]

array([143. , 181.5, 165. , 165. , 154. ])

In [10]:
#6
avg_disp_europe = df[df['origin'] == 2]['displacement'].to_numpy().mean()
avg_disp_europe

np.float64(109.14285714285714)

In [11]:
#7
matrix = df[['mpg', 'horsepower', 'weight']].to_numpy()
vector = np.array([1, 0.5, -0.2])

dot_product = matrix.dot(vector)
dot_product[:5]

array([-617.8, -641.1, -594.2, -595.6, -602.8])

In [12]:
#8
sorted_cars = df.sort_values('model year', ascending=False)
sorted_cars['car name'].head(5)

397         chevy s-10
396        ford ranger
395      dodge rampage
394          vw pickup
393    ford mustang gl
Name: car name, dtype: object

In [13]:
#9
correlation = np.corrcoef(df['mpg'], df['weight'])[0,1]
correlation

np.float64(-0.8317409332443352)

In [14]:
#10
cylinders = df['cylinders'].to_numpy()
mpg = df['mpg'].to_numpy()

for c in np.unique(cylinders):
    print(c, mpg[cylinders == c].mean())

3 20.55
4 29.28676470588235
5 27.366666666666664
6 19.985714285714284
8 14.963106796116506


##Pandas Problems

In [15]:
#1
df.head(10)
df.shape
df.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  398.000000   398.000000   
mean    23.514573    5.454774    193.425879  104.469388  2970.424623   
std      7.815984    1.701004    104.269838   38.199187   846.841774   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.500000    4.000000    104.250000   76.000000  2223.750000   
50%     23.000000    4.000000    148.500000   95.000000  2803.500000   
75%     29.000000    8.000000    262.000000  125.000000  3608.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model year      origin  
count    398.000000  398.000000  398.000000  
mean      15.568090   76.010050    1.572864  
std        2.757689    3.697627    0.802055  
min        8.000000   70.000000    1.000000  
25%       13.825000   73.000000    1.000000  
50%       15.500000   76.000000    1.000000  
75%       17.175000   79.000000    2.000000  
max       24.800000   82.000000    3.000000

In [16]:
#2
df_1975 = df[(df['model year'] == 75) & (df['weight'] < 3000)]
df_1975[['car name', 'weight', 'mpg']]

car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0

In [17]:
#3
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [18]:
#4
df['power_to_weight_ratio'] = df['horsepower'] / df['weight']
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model year  origin                   car name  power_to_weight_ratio  
0          70       1  chevrolet chevelle malibu               0.037100  
1          70       1          buick skylark 320               0.044679  
2          70       1         plymouth satellite               0.043655  
3          70       1              amc rebel sst               0.043694  
4          70       1                ford torino               0.040591

In [19]:
#5
df.groupby('origin')['mpg'].mean()

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64

In [20]:
#6
df.sort_values('mpg', ascending=False)[['car name', 'mpg']].head(10)

car name   mpg
322                        mazda glc  46.6
329              honda civic 1500 gl  44.6
325             vw rabbit c (diesel)  44.3
394                        vw pickup  44.0
326               vw dasher (diesel)  43.4
244  volkswagen rabbit custom diesel  43.1
309                        vw rabbit  41.5
330             renault lecar deluxe  40.9
324                       datsun 210  40.8
247                   datsun b210 gx  39.4

In [21]:
#7
def performance_score(row):
    return (row['mpg'] * row['acceleration']) / row['weight']

df['performance_score'] = df.apply(performance_score, axis=1)
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model year  origin                   car name  power_to_weight_ratio  \
0          70       1  chevrolet chevelle malibu               0.037100   
1          70       1          buick skylark 320               0.044679   
2          70       1         plymouth satellite               0.043655   
3          70       1              amc rebel sst               0.043694   
4          70       1                ford torino               0.040591   

   performance_score  
0           0.061644  
1           0.046710  
2           0.057625  
3           0.055928  
4           0.051754

In [22]:
#8
year_summary = df.groupby('model year')[['mpg','weight','horsepower']].mean()
year_summary

mpg       weight  horsepower
model year                                    
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.945335
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.609977
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   79.342716
81          30.334483  2522.931034   81.843772
82          31.709677  2453.548387   82.208690

In [23]:
#9
high_mpg = df[df['mpg'] > 30][['mpg','cylinders','horsepower','weight']]
high_mpg.to_csv('high_mpg_cars.csv', index=False)

In [24]:
files.download('high_mpg_cars.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [25]:
#10
Q1 = df['mpg'].quantile(0.25)
Q3 = df['mpg'].quantile(0.75)
IQR = Q3 - Q1

outliers = df[(df['mpg'] < Q1 - 1.5*IQR) | (df['mpg'] > Q3 + 1.5*IQR)]
outliers[['car name', 'mpg', 'model year']]

car name   mpg  model year
322  mazda glc  46.6          80